// Values already sorted
export const olympiquesAndparalympiques = [
  'Fédération française de badminton',
  'Fédération française de basketball',
  'Fédération française de boxe',
  'Fédération française de canoë-kayak et sports de pagaie',
  'Fédération française de cyclisme',
  'Fédération française de danse',
  'Fédération française de football',
  'Fédération française de golf',
  'Fédération française de gymnastique',
  'Fédération française de handball',
  'Fédération française de hockey',
  'Fédération française de hockey sur glace',
  'Fédération française de judo, jujitsu, kendo et disciplines associées',
  'Fédération française de la montagne et de l’escalade',
  'Fédération française de lutte',
  'Fédération française de natation',
  'Fédération française de pentathlon moderne',
  'Fédération française de roller et skateboard',
  'Fédération française de rugby',
  'Fédération française de ski',
  'Fédération française de surf',
  'Fédération française de taekwondo et disciplines associées',
  'Fédération française de tennis',
  'Fédération française de tennis de table',
  'Fédération française de tir',
  'Fédération française de tir à l’arc',
  'Fédération française de triathlon et disciplines enchainées',
  'Fédération française de voile',
  'Fédération française de volley',
  'Fédération française des sports de glace',
  'Fédération française du sport adapté',
  'Fédération française d’athlétisme Fédération française d’aviron',
  'Fédération française d’escrime',
  'Fédération française d’haltérophilie, musculation',
  'Fédération française d’équitation',
  'Fédération française handisport',
];

// Values already sorted
export const multisportsAndaffinitaires = [
  'Fédération Nationale des Offices municipaux des sports (FNOMS)',
  'Fédération Sportive Educative de l’Enseignement Catholique (USGEL)',
  'Fédération des clubs de la défense',
  'Fédération française culturelle et sportive maccabi',
  'Fédération française des clubs alpins et de montagne',
  'Fédération française des clubs omnisports (FFCO)',
  'Fédération française des sports populaires',
  'Fédération française du sport d’entreprise',
  'Fédération française du sport travailliste (FFST)',
  'Fédération française du sport universitaire',
  'Fédération française d’éducation physique et de gymnastique volontaire',
  'Fédération française omnisports des personnels de l’éducation nationale de la jeunesse et sports',
  'Fédération française sports pour tous',
  'Fédération nationale du sport en milieu rural',
  'Fédération sportive de la police nationale',
  'Fédération sportive des ASPTT',
  'Fédération sportive et culturelle de France (FSCF)',
  'Fédération sportive et gymnique du travail (FSGT)',
  'UCPA',
  'Union française des œuvres laïques d’éducation physique (UFOLEP)',
  'Union nationale des clubs universitaires (UNCU)',
  'Union nationale sportive Léo Lagrange',
];

// Values already sorted
export const unisport = [
  'Fédération de boxe américaine et disciplines associées',
  'Fédération de double dutch',
  'Fédération de voitures radio commandées',
  'Fédération des arts énergétiques et martiaux chinois',
  'Fédération des sports et loisirs canins',
  'Fédération française aéronautique Fédération française d’hélicoptère',
  'Fédération française de Kick Boxing, Muay Thaï et disciplines associées',
  'Fédération française de ball-trap',
  'Fédération française de ballon au poing',
  'Fédération française de baseball, softball',
  'Fédération française de billard',
  'Fédération française de bowling et de sport de quilles',
  'Fédération française de char à voile',
  'Fédération française de course camarguaise',
  'Fédération française de course d’orientation',
  'Fédération française de cyclotourisme',
  'Fédération française de flying disc',
  'Fédération française de football américain',
  'Fédération française de force',
  'Fédération française de javelot tir sur cible',
  'Fédération française de jeu de balle au tambourin',
  'Fédération française de jeu de paume',
  'Fédération française de joute et sauvetage nautique',
  'Fédération française de karaté et disciplines associées',
  'Fédération française de la course landaise',
  'Fédération française de la randonnée pédestre',
  'Fédération française de longue paume',
  'Fédération française de motocyclisme',
  'Fédération française de parachutisme',
  'Fédération française de pelote basque',
  'Fédération française de planeur ultraléger motorisé',
  'Fédération française de polo',
  'Fédération française de pulka et traineau à chiens',
  'Fédération française de pétanque et jeu provençal',
  'Fédération française de rugby à XIII',
  'Fédération française de sauvetage et de secourisme',
  'Fédération française de savate, boxe française et disciplines associées',
  'Fédération française de ski nautique et de wakeboard',
  'Fédération française de spéléologie',
  'Fédération française de squash',
  'Fédération française de vol en planeur',
  'Fédération française de vol libre',
  'Fédération française des pêches sportives',
  'Fédération française des sports de traîneau, de ski/vtt joëring et de canicross',
  'Fédération française des échecs',
  'Fédération française du sport automobile',
  'Fédération française du sport boules',
  'Fédération française d’aéromodélisme',
  'Fédération française d’aérostation',
  'Fédération française d’aïkido et de budo',
  'Fédération française d’aïkido, d’aïkibudo et affinitaires',
  'Fédération française d’études et sports sous-marins',
  'Fédération française motonautique',
  'Fédération française sportive de twirling bâton',
  'Fédération nautique de pêche sportive en apnée',
];
